### ISSUE TITLE
Wie bekomme ich dieses Projekt in meine Waffle.IO Übersicht?

### ISSUE THREAD

**Issue by andreasgremm** [Crayfish68/IoT-Workshop-for-Students-DYT-CA-Technologies#5]
Ich kann zwar einen join aufrufen ... aber sehe nur meine eigenen Projekte in "HOME"

**Comment by ThomasStolt** [comment]
waffle.io wurde wohl zugemacht, daher mache ich diesen Issue auch zu. :)

**Comment by ThomasStolt** [comment]
Closed
